### ISSUE TITLE
Simpler implementation suggestion

### ISSUE THREAD

**Issue by simara-svatopluk** [grifart/enum#5]
Hi, when I read the `Enum`, I find a lots of abstract concepts that are difficult to understand... is anything wrong with this implementation?

```php
abstract class DayOfWeek
{

    protected const MONDAY = 'monday';
    protected const TUESDAY = 'tuesday';

    public abstract function nextDay(): self;

    public static function MONDAY(): self
    {
        return new class extends DayOfWeek
        {
            public function nextDay(): DayOfWeek
            {
                return DayOfWeek::TUESDAY();
            }
        };
    }

    public static function TUESDAY(): self
    {
        return new class extends DayOfWeek
        {
            public function nextDay(): DayOfWeek
            {
                return DayOfWeek::WEDNESDAY();
            }
        };
    }
}
```

**Comment by jkuchar** [comment]
Tt does not preserve equality.

```php
DayOfWeek::MONDAY() === DayOfWeek::MONDAY(); // false - WTF?!
```

**Comment by simara-svatopluk** [comment]
you are right, I didn't realize it.....
but is this how value objects should be compared? When two value objects contain the same properties, we consider value objects the same eg.:
```php
class VO {
    public $string = 'default';
}

$a = new VO();
$b = new VO();

$a !== $b // yes, they are not the same object
$a == $b // they represent the same value
```

In the end, I think value objects should be compared by `==` or `equal` method, not by identity `===`

**Comment by jkuchar** [comment]
Problem with comparing using `==` is that you assume that VO supports that and that is **implicitly** implements that. That is not always the case and there is no way how to know this from outside.

So I **never** use `==` for objects comparison as it **implicitly** implements equals methods by using (`==` operator) for all vaues and that can be wrong and there is *no way how object can stop you from doing this*. 

This is bad as you are implementing what is equal and what is not outside of object.

(TL;DR: `==` makes sence only on primitive types)

--------

Only proper way comparing `VO` is `equals` method.

`===` is identity comparison and I have implemented this in my enumeration as every value can ever exist only once inside the system (singleton).

However I would still recommend to use `equals` method as then what is equals and what is not knowledge is kept inside of the object.

**Comment by simara-svatopluk** [comment]
Ou, I didn't want to stuck on `==` comparison, `equal` is better. period.

**Comment by jkuchar** [comment]
I'm going to reopen this as we agreed but only on using equals. Not if it makes sense provide also `===` identity comparison.

**Comment by jkuchar** [comment]
As I'm trying to mimic Java enum here, there exists only one instance per value, so comparing `===` makes sense. Also I presonally really like that `===` and `==` behaves now the same way, so you can use `switch`, `in_array`, etc and it does not break things. I consider this good usability and theoretical cleanliness.

**Comment by simara-svatopluk** [comment]
If the goal is to mimic Java enums, then it is a fine implementation.
If the goal is to show value objects from DDD, then I disagree with the fact the implementation forces me to a single value object instance per system.

**Comment by jkuchar** [comment]
I consider that decision as quite pragramatic and useful for most use cases.

I would be very happy if you show my why it is useful to have more enum value instances in the app. I still do not see the point. As enumeration is closed set of predefined values.

**Comment by simara-svatopluk** [comment]
When I look back why did I create this issue, then the reason is that I implemented the same behavior without your library. The only problem is that it cannot be compared by identity comparison, but there must be also a method for comparing.
