### ISSUE TITLE
Interface instead of abstract class

### ISSUE THREAD

**Issue by simara-svatopluk** [grifart/enum#6]
Hi, personally I don't like abstract classes and static calls... What do You think about this implementation?

```php
interface DayOfWeek
{
    public function nextDay(): self;
}

class Monday implements DayOfWeek
{
    public function nextDay(): DayOfWeek
    {
        return new Tuesday();
    }
}

class Tuesday implements DayOfWeek
{
    public function nextDay(): DayOfWeek
    {
        return new Tuesday();
    }
}
```

**Comment by jkuchar** [comment]
That is definitely possible. I will add this to my test cases to proof, that this actually works. ;)

**Comment by jkuchar** [comment]
It kind of works, but what exactly is the problem with global static register for enum values? This is what enum is by defintion. Look at Java for example. ;)

Interface is nice, problem is that there is no way how to actually receive value. There is need for some kind of static register for storing them. So you will need 4rd class anyway.

You are right in #5 if we get rid of identity comparison (witch is basically convenient feature) then we can have more instances of the same value and there will be simpler enum implementation. But it has some drawbacks. Consider this code:

```php
class Tuesday implements DayOfWeek
{
    public $x;
    public function nextDay(): DayOfWeek
    {
        return new Tuesday();
    }
}

$thuesday1 = new Thuesday();
$thuesday2 = new Thuesday();

$thuesday2->x = 5;
```

As I have two objects I have **dynamically** declared new enum value. That is against definition of what enumeration is. **So no, this is not the way.**

Look at [wiki: Java enum](https://en.wikipedia.org/wiki/Enumerated_type#Java), they are generating instance for each value. That makes sense. As constructing that instance must **not** depend on environment, because enum value must be fully determined just by pair `(enum type, value identifier)`.

**Comment by jkuchar** [comment]
I'm still interested in your motivation...

> personally I don't like abstract classes and static calls...

Are there any arguments hidden under this or just feelings? ;)

**Comment by simara-svatopluk** [comment]
This discussion is getting out of control, but it is great!

> what exactly is the problem with global static register for enum values?

This sentence simply embarrass me. I see `global` and i feel *ehh*, I see `static` and I feel *ehh*, and when I see `global static`, then I feel *eehhhh* :-D  
I cannot say I have a great argument against this, these are my feelings. Every time I see something global, I have an alert in my head - this could be problematic. It immediately reminds me global variables, global state - things I want to avoid.  
As same feeling hits me when I see static - it is something unchangeable, potentially problematic.

> Why do I don't like abstract classes and static calls...

I will explain only `abstract` as static is explained earlier. In your example we have a behavior `nextDay()` and we say that `Monday`, `Thursday`... fulfills this behavior. This imply me an interface. And since objects doesn't share any internal behavior or properties, interface is my choice.  
If there is something to share, I would maybe, maybe use abstract, but still interface is usually my choice because it doesn't force me how to do the implementation, abstract class does.

~One~ Multiple final ideas that crystallized in my head about value objects and registers...
* I find great that I can have multiple "same" value objects in my system and I don't care which is it. This makes tests easier, thinking easier. So I want to have the possibility to have multiple "same" value objects. 
* It could be extremely practical to have a register for value objects that produces only one instance at a time, for resources reasons if you have tones of usages of value objects. But I think that this is a different responsibility - value object is responsible for behavior, register is responsible for keeping and returning the same value objects. And since I see two responsibilities, I want to separate them - create a separated register. And since this register is separated, maybe, maybe it doesn't have to be static, and maybe we find it useful to have it static, singleton.  
*But in fact I don't like singletons :-P*
  * and now I realized that you already mentioned this 
    > Interface is nice, problem is that there is no way how to actually receive value. There is need for some kind of static register for storing them. So you will need 4rd class anyway.

    Yes, and I even want to have 4th class

> `$thuesday2->x = 5;`

In this example I don't see a problem that implementation have something extra, because everywhere in code we will use `DayOfWeek`, so we can call only `nextDay`, not `->x`.

> As I have two objects I have dynamically declared new enum value. That is against definition of what enumeration is. So no, this is not the way.

I think this is not a problem. In this example you have broken immutability of value object. We shouldn't do this. Core review or code sniff have to reveal this break and we shouldn't be allowed to do this.

Long answer... did I forget something?

**Comment by jkuchar** [comment]
I still do not agree. I try to mimic Java's enum behaviour as close as possible. And from definition of enumeration, there must exist just enumerated values and no other, because it is enumeration :)
